services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80" 
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
  nodejs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis-data:



